### ISSUE TITLE
Build flag to enable/disable pushing the docker images 

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/TeaStore#104]
Currently local builds are impossible, as the build enforces pushing to a repository

**Comment by joakimkistowski** [comment]
Docker images are only built and pushed with the `docker` profile enabled in Maven.  
For a regular, war-only build, run:

```bash
$ mvn clean install
```

Docker images are built using using the Spotify Docker plugin. It will push the new TeaStore version to DockerHub by default. To push your modified TeaStore version to your own Docker registry, you need to perform 2 actions.  
First, change the target registry in the Dockerfiles. The easiest way to do this is using sed, but you can also just use a text editor of your choice:

```bash
sed -i "s|.*FROM descartesresearch/|FROM MYREGISTRY.com/|g" ./utilities/tools.descartes.teastore.dockerbase/WebuiDockerfile/Dockerfile
sed -i "s|.*FROM descartesresearch/|FROM MYREGISTRY.com/|g" ./utilities/tools.descartes.teastore.dockerbase/ServiceDockerfile/Dockerfile
sed -i "s|.*FROM descartesresearch/|FROM MYREGISTRY.com/|g" ./utilities/tools.descartes.teastore.kieker/Dockerfile
```

Next, run maven with the `docker` profile enabled and specify your private registry:

```bash
$ mvn clean install -Pdocker  -Ddockerrepository=MYREGISTRY.com
```
