### ISSUE TITLE
Dockerfiles should make use of the dockerrepository environment variable

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/TeaStore#105]
Currently, most dockerfiles use hardcoded registries. We should update these to use the value of the environment variable $dockerrepository.

**Comment by joakimkistowski** [comment]
I decided to go the opposite way and remove the environment variable instead. Docker images are now built exclusively from the Dockerfiles, without using Maven. Maven is now only building the WARs, which are then packaged by calling `docker build` separately. This way, the target registry is configured exclusively in the Dockerfiles. This should be way more intuitive for Docker users.
