### ISSUE TITLE
Configuire database connection fully from code instead of persistence.xml files

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/TeaStore#108]
The persistence files are quite cumbersome, move the configuration to startup code instead.

**Comment by joakimkistowski** [comment]
Persistence now uses a Java env variable to enable the testing in-memory database. The variable can be set in Tomcat's `context.xml` and is automatically set in a dev-`context.xml` that is auto-deployed with Persistence in the development environment. The behavior is documented here: https://github.com/DescartesResearch/TeaStore/wiki/Getting-Started#3-database-in-development-environment
