### ISSUE TITLE
Documentation on running teastore-all seems incorrect

### ISSUE THREAD

**Issue by llarsson** [DescartesResearch/TeaStore#138]
The [documentation on running as a single container](https://github.com/DescartesResearch/TeaStore/wiki/Getting-Started#1-run-as-a-single-container) seems incorrect, as I get errors when trying to connect to the database instance. 

Using good old-fashined [docker links](https://docs.docker.com/network/links/) makes it work, however, with lines such as:

```
docker run -p 3306:3306 -d --name teastore-db descartesresearch/teastore-db
docker run -e "DB_HOST=teastore-db" -p 8080:8080 -d --link teastore-db:teastore-db --name teastore-all descartesresearch/teastore-all
```

**Comment by SimonEismann** [comment]
Good find, I was able to reproduce this issue. It seems the current setup leave the persistence unable to contact the db.

Your solution using the links worked for me, so I've updated the documentation accordingly. Thank you for your contribution.
