### ISSUE TITLE
Low res main screen picture.

### ISSUE THREAD

**Issue by Smidra** [DescartesResearch/TeaStore#147]
Hi, the main picture is very blocky and low resolution.
`services/tools.descartes.teastore.webui/src/main/webapp/images/front.png`

I've made a hi-resolution one while lowering the size. Want to use it? :)

**Old:**
![old-front](https://user-images.githubusercontent.com/25660869/79271282-d237e600-7e9f-11ea-85f4-82d1f66537d6.png)
**New:**
![teastore-logo](https://user-images.githubusercontent.com/25660869/79271199-b3395400-7e9f-11ea-930e-305e2827598d.png)

**Comment by SimonEismann** [comment]
This looks great, we'll definitely use this one.

**Comment by SimonEismann** [comment]
Also included in PR #149, new logo looks a lot better :-)
