### ISSUE TITLE
failure when running multiple instances

### ISSUE THREAD

**Issue by MohamadHamamah** [DescartesResearch/TeaStore#152]
Hello,

I am trying to use this benchmark for my research. I am using kubernetes deployments and I found that the application works fine when running only one instance of each service. When I use multiple instances for each service, the services status become off every few seconds. The more I increase the number of instances, the more frequent the services go off.

I have tried Cluster-ip and Ribbon deployment and had the same problem in both.
I am not too familiar with kubernetes. Is that behavior normal? if it is not, does that related to kubernetes or your app?

**Comment by SimonEismann** [comment]
Hey @MohamadHamamah,

the TeaStore should support multiple service instances in Kubernetes. To help us track down what is going on here, could you explain in a bit more detail what you mean by the services status becomes off?

Additionally, could you post how you adapted the .yaml files to replicate the service instances?

Maybe @kasokz has some ideas what other files/logs could help track this issue down?

**Comment by MohamadHamamah** [comment]
thanks for your fast response.

I mean by service status becomes off: the status of the service in status page which will be ok or ok and populated (depending on the service) if the service is working fine. 

To replicate the services I tried many ways and I got the same behavior. but the one I am interested in is to replicate the services using kubernetes auto-scaler. You can try this for example:
kubectl apply -f teastore-clusterip.yaml
kubectl autoscale -f teastore-ribbon.yaml --min=7 --max=7 --cpu-percent=70 

The only change I made to the clusterip file is that I specified resources limits and requests. The same applies to ribbon.

I ran into the problem while stressing the app (using the http load generator) to monitor the auto-scaler behavior and I thought that the problem is related to the continuous change in number of instances. but even with fixing the number of pods without any load as in the previous scenario I have the same problem.

**Comment by SimonEismann** [comment]
It looks like you are configuring everything correctly. A potential reason could be that the pods crash or are restarted by kubernetes. Could you check if there are any container restarts? 

https://sysdig.com/blog/debug-kubernetes-crashloopbackoff/

**Comment by MohamadHamamah** [comment]
The pods are not restarting:
<img width="512" alt="Screen Shot 2020-06-02 at 16 42 46" src="https://user-images.githubusercontent.com/13808733/83533872-69103e80-a4f0-11ea-944f-4dc57b3b2eaa.png">

Also as far as I know the crash loop backoff can be detected from the pods events which is not the case here:
<img width="1186" alt="Screen Shot 2020-06-02 at 16 48 43" src="https://user-images.githubusercontent.com/13808733/83534295-f6539300-a4f0-11ea-99dd-db5a4bdf857f.png">

**Comment by SimonEismann** [comment]
Alright, no restarts it seems. 

What seems a bit unusual about your setup is that you also have 7 registry instances. This might be causing some issues, as the teastore does not support registry replication (which would also only be required with 1000+ service instances).

Could you try moving the registry definition to a separate yaml file and only scale the remaining services?

**Comment by MohamadHamamah** [comment]
Thanks a lot. I am really grateful for your help.
It was the registry causing that issue.

**Comment by SimonEismann** [comment]
Glad to hear I was able to help!

While we are at it, I am also unsure if replicating the database works. We have never tested this up to now, as so far in our experiments, with up to 7.000 req/s we never required more than one database instance. 

Closing the issue for now, feel free to reopen if you run into any additional issues.
