### ISSUE TITLE
development env

### ISSUE THREAD

**Issue by prathjan** [DescartesResearch/TeaStore#199]
cant find the dev env setup

**Comment by SimonEismann** [comment]
Hey, could you go into a bit of detail on what exactly you are looking for? 

If you are looking to customize the TeaStore, we have some instructions on how to do this here: https://github.com/DescartesResearch/TeaStore/wiki/Customizing-the-TeaStore

**Comment by prathjan** [comment]
@SimonEismann I was not able to find:  https://github.com/DescartesResearch/TeaStore/wiki/Getting-Started#setup-and-run-the-teastore-development-environment
