### ISSUE TITLE
Option to build TeaStore as a monolithic (single container) application no longer available

### ISSUE THREAD

**Issue by ramironagles** [DescartesResearch/TeaStore#216]
There used to be an option to build TeaStore as a monolithic application (v 1.3.8) but it is not the case anymore.
If I load v 1.3.8 the links take me to the current version and there is a reference to the TeaStore wiki where the "Deploy the TeaStore in one or several Java Application Container(s)" is offered but the actual link  (https://github.com/DescartesResearch/TeaStore/wiki/Getting-Started#deploy-the-pet-supply-store-in-java-application-containers) is broken and/or misleading (why is it talking about the 'pet-supply-store'?)

**Comment by SimonEismann** [comment]
Hi ramironagles,

we recently discontinued the `teastore-all` image, since it became hard to maintain due to its outdated approach.

Do you need the newest TeaStore version? Otherwise, you could try the old `teastore-all` images:
https://hub.docker.com/r/descartesresearch/teastore-all

In the future, we were considering offering a new` teastore-all` image that uses docker-in-docker to run all services inside a single container as this solution would be much easier to maintain. This was not on the roadmap currently, since we were not aware of anybody using the `teastore-all` image. 

PS: PetSupplyStore was the name we used internally before settling on TeaStore, so the link you found is pretty old :) Where exactly is that link? Then I'll fix that :)

**Comment by ramironagles** [comment]
Simon,

  *   Thank you SO much for taking the time to address my question.
  *   Let me begin by expressing my appreciation for the work you guys have done with TeaStore!... this is a life-saver for so many of us that need a real application for benchmarking, testing and concept proving.
  *   I work for Cisco-AppDynamics and we are trying to build a cloud-migration workshop to illustrate the benefits of the cloud and to show how performance-monitoring will help in the migration process and that is why we need a monolithic version of TeaStore.
  *   We want to instrument a monolithic version of TeaStore and then compare its performance with that of the micro-services version of TeaStore side-by-side so people can see the benefits and experience how AppDynamics can assist on that process.
  *   Actually, the ‘hard to maintain’ version of TeaStore is, probably, what we need (monolithic) so I will explore the teastore-all link you shared with me (thank you SO much for that!!!!)
  *   My initial hope was that if I went back long enough into TeaStore repo I would come across the version that still had the monolithic option and that is when I saw v 1.3.8 that mentioned the one-container option but the links didn’t work – there, in v 1.3.8<https://github.com/DescartesResearch/TeaStore/tree/v1.3.8> is where I found the pet-supply-store link
***@***.***

Regards
Ramiro Nagles
[https://www.cisco.com/c/dam/m/en_us/signaturetool/appdynamics/appd_logo_with_bg.png]
Ramiro Nagles
Solutions Engineer
AppDynamics
***@***.******@***.***>
[signature_296619443][signature_649371075]

From: SimonEismann ***@***.***>
Date: Friday, June 3, 2022 at 1:08 PM
To: DescartesResearch/TeaStore ***@***.***>
Cc: Ramiro Nagles (rnagles) ***@***.***>, Author ***@***.***>
Subject: Re: [DescartesResearch/TeaStore] Option to build TeaStore as a monolithic (single container) application no longer available (Issue #216)

Hi ramironagles,

we recently discontinued the teastore-all image, since it became hard to maintain due to its outdated approach.

Do you need the newest TeaStore version? Otherwise, you could try the old teastore-all images:
https://hub.docker.com/r/descartesresearch/teastore-all

In the future, we were considering offering a new teastore-all image that uses docker-in-docker to run all services inside a single container as this solution would be much easier to maintain. This was not on the roadmap currently, since we were not aware of anybody using the teastore-all image.

PS: PetSupplyStore was the name we used internally before settling on TeaStore, so the link you found is pretty old :) Where exactly is that link? Then I'll fix that :)

**Comment by ramironagles** [comment]
I was wondering if there is any chance for us to clone/fork the source code repository used to build the monolithic teastore-all image (the link points to a docker image but not the source code repo).  
We need to introduce some 'bugs' in the application to illustrate some performance-monitoring scenarios and that is why we need the source code so we can modify it and re-build it.

**Comment by ramironagles** [comment]
Simon,
Thank you so much for looking into this!.   I would be very interested in setting up a call to discuss what needs to be done to convert TeaStore in a 100% monolithic application. 
Please let me know what dates and times work for you this week so we can schedule the call.  I am located in the US CST time zone.
Thanks in advance.

**Comment by SimonEismann** [comment]
Closing this since we resolved this offline :)

**Comment by ramironagles** [comment]
Simon,
Thanks a lot for all the help!.
Fortunately we managed to accomplish what we were looking for in less than a week using our home-made application.
Having said that, TeaStore is still a fundamental component of our workshops and initiatives so I hope we can engage back with you and your team in the event we might need some guidance.
Please let me know if you want to be kept in the loop in regards to the ways we are using TeaStore in the future.

Regards
Ramiro Nagles
[https://www.cisco.com/c/dam/m/en_us/signaturetool/appdynamics/appd_logo_with_bg.png]
Ramiro Nagles
Solutions Engineer
AppDynamics
***@***.******@***.***>
[signature_2298816988][signature_452914695]

From: SimonEismann ***@***.***>
Date: Tuesday, July 26, 2022 at 5:53 AM
To: DescartesResearch/TeaStore ***@***.***>
Cc: Ramiro Nagles (rnagles) ***@***.***>, Author ***@***.***>
Subject: Re: [DescartesResearch/TeaStore] Option to build TeaStore as a monolithic (single container) application no longer available (Issue #216)

Closing this since we resolved this offline :)

**Comment by SimonEismann** [comment]
Great to hear that everything worked out!

`Please let me know if you want to be kept in the loop in regards to the ways we are using TeaStore in the future.`

Of course, we are always excited to hear how people are using the TeaStore :)
