### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by Angi2412** [DescartesResearch/TeaStore#221]
Hi,
I used the TeaStore in my publication, which can be found [here](https://link.springer.com/chapter/10.1007/978-3-031-12597-3_15). Please add it to your publication section :)

`Horn, A., Fard, H.M., Wolf, F. (2022). Multi-objective Hybrid Autoscaling of Microservices in Kubernetes Clusters. In: Cano, J., Trinder, P. (eds) Euro-Par 2022: Parallel Processing. Euro-Par 2022. Lecture Notes in Computer Science, vol 13440. Springer, Cham. https://doi.org/10.1007/978-3-031-12597-3_15`

**Comment by SimonEismann** [comment]
Hi @Angi2412, congratulations on the accepted paper, and great to hear that the TeaStore was useful. The paper definitely looks interesting :)

I've added it to the examples of the teastore.
