### ISSUE TITLE
Kubernetes deployments are not labelled

### ISSUE THREAD

**Issue by hkayabilisim** [DescartesResearch/TeaStore#251]
Since the Kubernetes deployments are not labelled, 

# The problem
"app=teastore" labels are missing for the deployments.

# How to recreate the issue
* A clean Kubernetes cluster installation. In my setup, I'm using Rancher Desktop 1.9.1 which uses Kubernetes v1.27.3+k3s1.

      $ kubectl get nodes 
      NAME                   STATUS   ROLES                  AGE   VERSION
      lima-rancher-desktop   Ready    control-plane,master   87s   v1.27.3+k3s1

* Install TeaStore version.

      $ kubectl create -f https://raw.githubusercontent.com/DescartesResearch/TeaStore/master/examples/kubernetes/teastore-clusterip.yaml
      deployment.apps/teastore-db created
      service/teastore-db created
      deployment.apps/teastore-registry created
      service/teastore-registry created
      deployment.apps/teastore-persistence created
      service/teastore-persistence created
      deployment.apps/teastore-auth created
      service/teastore-auth created
      deployment.apps/teastore-image created
      service/teastore-image created
      deployment.apps/teastore-recommender created
      service/teastore-recommender created
      deployment.apps/teastore-webui created
      service/teastore-webui created

* Check pods,services and deployments to see if they are all installed

      $ kubectl get pods,services,deployments 
      NAME                                        READY   STATUS    RESTARTS   AGE
      pod/teastore-registry-689ffc5d95-8d2nz      1/1     Running   0          3m50s
      pod/teastore-recommender-747b6777fd-b5744   1/1     Running   0          3m50s
      pod/teastore-auth-79857b8dd-45c27           1/1     Running   0          3m50s
      pod/teastore-db-c47867b8d-v6tcp             1/1     Running   0          3m50s
      pod/teastore-webui-684b444996-sg6wg         1/1     Running   0          3m49s
      pod/teastore-persistence-5bbb48fcd5-2dlcp   1/1     Running   0          3m50s
      pod/teastore-image-ff959ffbb-t96ps          1/1     Running   0          3m50s
      
      NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
      service/kubernetes             ClusterIP   10.43.0.1       <none>        443/TCP          9m17s
      service/teastore-db            ClusterIP   10.43.51.164    <none>        3306/TCP         3m50s
      service/teastore-registry      ClusterIP   10.43.130.186   <none>        8080/TCP         3m50s
      service/teastore-persistence   ClusterIP   10.43.39.177    <none>        8080/TCP         3m50s
      service/teastore-auth          ClusterIP   10.43.92.185    <none>        8080/TCP         3m50s
      service/teastore-image         ClusterIP   10.43.160.51    <none>        8080/TCP         3m50s
      service/teastore-recommender   ClusterIP   10.43.198.147   <none>        8080/TCP         3m50s
      service/teastore-webui         NodePort    10.43.180.162   <none>        8080:30080/TCP   3m50s
      
      NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
      deployment.apps/teastore-registry      1/1     1            1           3m50s
      deployment.apps/teastore-auth          1/1     1            1           3m50s
      deployment.apps/teastore-recommender   1/1     1            1           3m50s
      deployment.apps/teastore-db            1/1     1            1           3m50s
      deployment.apps/teastore-webui         1/1     1            1           3m50s
      deployment.apps/teastore-persistence   1/1     1            1           3m50s
      deployment.apps/teastore-image         1/1     1            1           3m50s

* List the same resources via "app=teastore" selection. **You'll see that the deployments are not listed.**

      $ kubectl get pods,services,deployments -l app=teastore
      NAME                                        READY   STATUS    RESTARTS   AGE
      pod/teastore-registry-689ffc5d95-8d2nz      1/1     Running   0          5m30s
      pod/teastore-recommender-747b6777fd-b5744   1/1     Running   0          5m30s
      pod/teastore-auth-79857b8dd-45c27           1/1     Running   0          5m30s
      pod/teastore-db-c47867b8d-v6tcp             1/1     Running   0          5m30s
      pod/teastore-webui-684b444996-sg6wg         1/1     Running   0          5m29s
      pod/teastore-persistence-5bbb48fcd5-2dlcp   1/1     Running   0          5m30s
      pod/teastore-image-ff959ffbb-t96ps          1/1     Running   0          5m30s
      
      NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
      service/teastore-db            ClusterIP   10.43.51.164    <none>        3306/TCP         5m30s
      service/teastore-registry      ClusterIP   10.43.130.186   <none>        8080/TCP         5m30s
      service/teastore-persistence   ClusterIP   10.43.39.177    <none>        8080/TCP         5m30s
      service/teastore-auth          ClusterIP   10.43.92.185    <none>        8080/TCP         5m30s
      service/teastore-image         ClusterIP   10.43.160.51    <none>        8080/TCP         5m30s
      service/teastore-recommender   ClusterIP   10.43.198.147   <none>        8080/TCP         5m30s
      service/teastore-webui         NodePort    10.43.180.162   <none>        8080:30080/TCP   5m30s

I've also tested on Minikube 1.25.3, the situation is still the same: deployments are not listed on "app=teastore" filter. 

# Why this is important
Because when I want to delete all TeaStore-related resources, I use "app=teastore" filter as suggested in the documentation. However, since the deployments cannot be filtered, they cannot be deleted in one shot.

**Comment by SimonEismann** [comment]
Good catch, thanks for adding this!

**Comment by SimonEismann** [comment]
Closing this, feel free to reopen in case this is not resolved
