### ISSUE TITLE
Tracing with Jaeger

### ISSUE THREAD

**Issue by laci9** [DescartesResearch/TeaStore#258]
Hi,
I've tried to trace the system with Jaeger by sidecar injection. In Jaeger UI, I can see all the traces with correct spans but everything has the same operation name **op**. Is it possible to trace the system and be able to see correct operation names and has someone some experience with that? Thank you for your answer.

**Comment by SimonEismann** [comment]
Hi @laci9, I unfortunately don't have any experience with instrumenting the TeaStore via Jaeger in Kubernetes. 

Could you add a screenshot/example traces to better highlight your issue? Maybe someone with more Jaeger experience comes across this issue :)

**Comment by laci9** [comment]
Hi @SimonEismann, thank you for your answer. 

I've used [this tutorial](https://www.jaegertracing.io/docs/1.49/operator/) to set up Jaeger for monitoring and in the screenshot below can be seen that all operation names are just **op**. I'm using Jaeger version 1.49 and after some investigation I've found out that Jaeger is not using openTracing anymore (from version 1.35 higher) but openTelemetry, so that might be causing issues, but I'm not really sure if that is the root cause as all traces have correct structure.

<img width="1432" alt="Snímka obrazovky 2023-11-14 o 19 24 06" src="https://github.com/DescartesResearch/TeaStore/assets/33522375/f92fc782-53ac-4efb-a8db-ab06a34196bd">
<img width="1084" alt="Snímka obrazovky 2023-11-14 o 19 24 24" src="https://github.com/DescartesResearch/TeaStore/assets/33522375/32a5b55d-e13b-459b-bb02-8db007139747">
<img width="1436" alt="Snímka obrazovky 2023-11-14 o 19 24 38" src="https://github.com/DescartesResearch/TeaStore/assets/33522375/3e65d8e3-2661-458c-8025-be2c7faaafa3">
<img width="1438" alt="Snímka obrazovky 2023-11-14 o 19 25 19" src="https://github.com/DescartesResearch/TeaStore/assets/33522375/fb046bc2-fdf1-4543-8108-750e744eae7e">
<img width="1426" alt="Snímka obrazovky 2023-11-14 o 19 27 01" src="https://github.com/DescartesResearch/TeaStore/assets/33522375/47d16f25-547d-4207-a2fd-5d259f5d1c8e">

**Comment by laci9** [comment]
I've found the root cause. When building span, it is hardcoded to set the oparation name to **op**.
Link to the source code, where it is set: [file](https://github.com/DescartesResearch/TeaStore/blob/master/utilities/tools.descartes.teastore.registryclient/src/main/java/tools/descartes/teastore/registryclient/tracing/Tracing.java#L104)

**Comment by laci9** [comment]
I solved my issue by adding a parameter to the [buildSpanFromHeaders](https://github.com/DescartesResearch/TeaStore/blob/master/utilities/tools.descartes.teastore.registryclient/src/main/java/tools/descartes/teastore/registryclient/tracing/Tracing.java#L103) method signature for operation name. Then from [extractCurrentSpan(HttpServletRequest request)](https://github.com/DescartesResearch/TeaStore/blob/master/utilities/tools.descartes.teastore.registryclient/src/main/java/tools/descartes/teastore/registryclient/tracing/Tracing.java#L70) can be sent also an URL or URI of the request as the operation name.

**Comment by SimonEismann** [comment]
Glad to hear that you were able to resolve this! Could you open up a PR with your changes? I think this might be useful for other users as well. Hardcoding the operation name to op seems ... not optimal :)

**Comment by laci9** [comment]
Sure, here's the [link](https://github.com/DescartesResearch/TeaStore/pull/260) to the pull request.
