### ISSUE TITLE
Recommender/Imageprovider are too verbose if the persistence is not available yet

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/TeaStore#71]
Incase database content has to be created during startup, you get the following spam. This obscures the message that everything is fine and the persistence is just generating content.

recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online
image_1        | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. IMAGE is waiting for it to come online
recommender_1  | [pool-3-thread-1] INFO tools.descartes.teastore.registryclient.RegistryClient - tools.descartes.teastore.persistence not online. RECOMMENDER is waiting for it to come online

**Comment by NSchmittUniWue** [comment]
Does this need to be fixed before release?

**Comment by SimonEismann** [comment]
Not necessarily, but should be easy to fix as there already is some code somewhere for the increasing time intervals

**Comment by NSchmittUniWue** [comment]
Fixed. The message is now only printed once.

Should have opened a new branch and merged it back but i forgot. Still, at least it is fixed.
